# Generated by Django 4.1.2 on 2022-10-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='main.room'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Employee'), (2, 'Client')], null=True),
        ),
    ]
