# Generated by Django 3.2.7 on 2022-10-20 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_scenario_rooms_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='main.game'),
        ),
    ]
