# Generated by Django 3.2.7 on 2022-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
