# Generated by Django 3.2.7 on 2022-10-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20221021_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameDetails',
        ),
    ]
